name: MVPModernized CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'source/MVPModernized/**'
      - '.github/workflows/mvp-modernized-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'source/MVPModernized/**'
      - '.github/workflows/mvp-modernized-ci.yml'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: 'source/MVPModernized'
  SOLUTION_FILE: 'source/MVPModernized/MVPModernized.sln'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Display .NET information
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
      
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test ${{ env.PROJECT_PATH }}/ProductApp.Tests/ProductApp.Tests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=unit-test-results.trx" --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage" --blame --blame-hang-timeout 5m

    # E2E Tests with proper Playwright setup and web app hosting
    - name: Build Web Application (for E2E tests)
      run: dotnet build ${{ env.PROJECT_PATH }}/ProductApp.Web/ProductApp.Web.csproj --configuration Debug --no-restore

    - name: Build E2E Tests Project
      run: dotnet build ${{ env.PROJECT_PATH }}/ProductApp.Tests.E2E/ProductApp.Tests.E2E.csproj --configuration Release

    - name: Install Playwright Browsers
      run: |
        cd ${{ env.PROJECT_PATH }}/ProductApp.Tests.E2E
        dotnet tool install --global Microsoft.Playwright.CLI || true
        playwright install chromium --with-deps
      shell: bash

    - name: Run E2E Tests (with integrated web app)
      run: dotnet test ${{ env.PROJECT_PATH }}/ProductApp.Tests.E2E/ProductApp.Tests.E2E.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=e2e-test-results.trx" --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage" --blame --blame-hang-timeout 15m
      env:
        ASPNETCORE_ENVIRONMENT: Development
        DOTNET_ENVIRONMENT: Development
        CI: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: |
          **/*.trx
          **/TestResults/**/*.coverage
          **/TestResults/**/*.xml
        retention-days: 30

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report-${{ matrix.os }}
        path: '**/TestResults/**/coverage.cobertura.xml'
        retention-days: 30

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build for analysis
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Debug --no-restore

    - name: Run .NET Format check
      run: dotnet format ${{ env.SOLUTION_FILE }} --verify-no-changes --verbosity diagnostic
      continue-on-error: true

    - name: Run Code Analysis  
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore /p:TreatWarningsAsErrors=false /p:EnableNETAnalyzers=true /p:AnalysisLevel=latest /p:EnforceCodeStyleInBuild=true

  publish-artifacts:
    name: Publish Build Artifacts
    runs-on: ubuntu-latest
    needs: [build-and-test, code-analysis]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

    - name: Publish Web Application
      run: dotnet publish ${{ env.PROJECT_PATH }}/ProductApp.Web/ProductApp.Web.csproj --configuration Release --output ./publish/web --runtime linux-x64 --self-contained false --no-build

    - name: Upload Web Application artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-application
        path: ./publish/web
        retention-days: 90

  test-report:
    name: Test Report Summary
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: always()
    
    steps:
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        pattern: test-results-*
        merge-multiple: true
        path: ./test-results

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Test Results'
        path: './test-results/**/*.trx'
        reporter: 'dotnet-trx'
        fail-on-error: false

  notify-status:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build-and-test, code-analysis]
    if: always() && github.event_name == 'pull_request'
    
    steps:
    - name: Determine status
      id: status
      run: |
        if [[ "${{ needs.build-and-test.result }}" == "success" && "${{ needs.code-analysis.result }}" == "success" ]]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "emoji=✅" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "emoji=❌" >> $GITHUB_OUTPUT
        fi

    - name: Create status comment
      uses: actions/github-script@v7
      with:
        script: |
          const status = '${{ steps.status.outputs.status }}';
          const emoji = '${{ steps.status.outputs.emoji }}';
          const workflow_url = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
          
          const body = `## ${emoji} MVPModernized CI Build Status: ${status.toUpperCase()}
          
          **Workflow Run:** [View Details](${workflow_url})
          **Commit:** \`${context.sha.substring(0, 7)}\`
          **Triggered by:** @${context.actor}
          
          | Check | Status |
          |-------|--------|
          | Build & Test | ${{ needs.build-and-test.result }} |
          | Code Analysis | ${{ needs.code-analysis.result }} |`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });